// Auto-generated by tools/build_aux_pool.py - do not edit by hand.
#pragma once

#define WORKING_SET 0
#define MAIN_MASK 1
#define TEST_STRING 2
#define TEST_FONT 3
#define DESIGNATOR_FONT 4
#define NUM_AUX_ANALOG 4
#define NUM_AUX_BUTTONS 16

static const uint16_t AUX_ANALOG_IDS[NUM_AUX_ANALOG] = {100, 101, 102, 103};
static const uint16_t AUX_BUTTON_IDS[NUM_AUX_BUTTONS] = {200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215};
